name: Update issue
# Note that syntax to refer to this issue is: {{ this_issue }} and for a
# previous one: {{ (this_issue | int ) - 1 }}
on:
  issues:
    types:
      - created
      - opened

jobs:
  reference_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install jinja-cli
      - name: basic Shell
        run: |
           gh issue view ${{ github.event.issue.html_url }} --json body -t '{{.body}}' >> text_body
           jinja -D "this_issue" "${{ github.event.issue.number }}" -D "this_org" "${{ github.repository_owner }}" -o text_body_out text_body
           gh issue edit ${{ github.event.issue.html_url }} --body-file text_body_out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
